### PR TITLE
Add Serverless(v1.2.1) Expressjs boilerplate

### PR DESCRIPTION
**Pull request by SharathHuddar**

### CODE REVIEW

**Comment by SharathHuddar** [comment]
@pmuens Added a link to expressjs app which uses serverless v1.2.1

**Comment by pmuens** [comment]
Thank you very much @SharathHuddar 🙌  Cool project! 🎉 

Could you do a quick rebase since I've added some stuff recently? Then we can merge it immediately!

**Comment by SharathHuddar** [comment]
@pmuens Rebase done!

**Comment by pmuens** [comment]
Merged! Thanks a lot!

**Pull request merged**
